### ISSUE TITLE
[Request] Add support for numpad keys

### ISSUE THREAD

**Issue by alexmozaidze** [lukexor/pix-engine#4]
I wanted to use numpad numbers for a tic-tac-toe game but realized that numpad keys aren't supported and are interpreted as `Key::Unknown` while normal number keys are `Key::NumX`. It would be cool if you added something like `Key::NumpadX` for numpad keys.

**Comment by lukexor** [comment]
Good catch! I'll get these added. I'd also accept a PR if you wanted to try and dig in. I primarily develop on a Mac so I don't have a numpad but I can test it out on my windows desktop

**Comment by lukexor** [comment]
Fixed in 0.5.1
