### ISSUE TITLE
[Bug?] `Builder::target_frame_rate` not working

### ISSUE THREAD

**Issue by alexmozaidze** [lukexor/pix-engine#5]
I set it to 30 but it doesn't do anything, it just continues to render at ~300 fps. I don't know how the gpu works so I can't tell if it's a bug or just a hardware limitation of some kind.

OS: Arch Linux
GPU: Intel Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Integrated Graphics Controller

**Comment by lukexor** [comment]
Interesting. I'll take a look, I haven't spent a lot of time testing the frame rate limiting, but it's supposed to work by checking the duration each loop and only calling on_update at that frame rate. It's also likely a recent change moved the FPS counting logic out of this, meaning that the reporting of FPS is what's actually inaccurate.

**Comment by alexmozaidze** [comment]
Fps reporting being inaccurate would explain that my CPU is half-resting while "drawing at ~300fps"

**Comment by lukexor** [comment]
Turned out to be a bug with initialization (and usage). target_frame_rate was not actually getting set or used correctly.

**Comment by lukexor** [comment]
Fixed in 0.5.1
