### ISSUE TITLE
[Request] Add an audio example

### ISSUE THREAD

**Issue by alexmozaidze** [lukexor/pix-engine#6]
An example with loading an audio file and playing it would be nice

**Comment by lukexor** [comment]
I agree! It's been on my to-do list. My main use of audio right now is from tetanes, where the nes emulation just gives samples. I'll look into getting some basic examples up soon along with wav and mp3 support.

**Comment by lukexor** [comment]
Added a basic audio example for the current audio support for generating raw samples and providing them to the audio queue. Audio synth is a vast and complicated topic. Additional audio support for callbacks, playing audio files (wav, mp3), additional sample formats, etc will be added in a future version with accompanying examples.

You could for example, use some third-party tool to generate an audio file containing raw 32-bit floating point samples in little-endian (which is the default sample format) and queue them.

One of the examples shows how to do this. The raw file was generated from a .wav file using `sox`, e.g.
```
sox input.wav --bits 32 --encoding floating-point --endian little output.raw
```
